In [91]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

## 코스피 라벨링 수정

In [92]:
df = pd.read_csv('코스피_라벨링.csv', index_col = 0)
df = df.reset_index(drop=True)

In [93]:
## 기업명이 중복되어서 잘못된부분이 있는지 확인

In [94]:
df[df['회사명'] == '(주)신성이엔지']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,이자_부실,현금흐름_부실,자본_부실,부실
4620,(주)신성이엔지,11930,2010/12,2.43,46860769.0,151699080.0,0,0,0,0,0,0,0
4621,(주)신성이엔지,11930,2011/12,-1.67,-37301003.0,151615459.0,-1,-1,0,0,0,0,0
4622,(주)신성이엔지,11930,2012/12,-3.08,-2517282.0,67178072.0,-1,-1,0,0,0,0,0
4623,(주)신성이엔지,11930,2013/12,-1.04,-1675298.0,44152010.0,-1,-1,0,1,1,0,1
4624,(주)신성이엔지,11930,2014/12,-0.28,-14292205.0,50282890.0,-1,-1,0,1,1,0,1
4625,(주)신성이엔지,11930,2015/12,0.78,7199165.0,62080991.0,-1,0,0,1,0,0,1
4626,(주)신성이엔지,11930,2016/12,-1.15,61987851.0,122275000.0,-1,0,0,1,0,0,1
4627,(주)신성이엔지,11930,2017/12,-0.52,-17144316.0,81810558.0,-1,-1,0,1,0,0,1
4628,(주)신성이엔지,11930,2018/12,-0.36,-44492773.0,114083620.0,-1,-1,0,1,0,0,1
4629,(주)신성이엔지,11930,2019/12,0.87,8904429.0,122176331.0,-1,0,0,1,0,0,1
4630,(주)신성이엔지,11930,2020/12,2.41,23991464.0,191465323.0,0,0,0,0,0,0,0
4631,(주)신성이엔지,11930,2021/12,0.60,-21302798.0,208038069.0,-1,-1,0,0,0,0,0
4632,(주)신성이엔지,11930,2022/12,4.30,-24003168.0,211169771.0,0,-1,0,0,0,0,0
4633,(주)신성이엔지,104110,2010/12,14.11,16035189.0,40511752.0,0,0,0,0,0,0,0
4634,(주)신성이엔지,104110,2011/12,10.42,-2343866.0,48321900.0,0,-1,0,0,0,0,0
4635,(주)신성이엔지,104110,2012/12,-0.32,14986358.0,39900700.0,-1,0,0,0,0,0,0
4636,(주)신성이엔지,104110,2013/12,9.13,6763269.0,47030473.0,0,0,0,0,0,0,0
4637,(주)신성이엔지,104110,2014/12,5.82,7033048.0,51297349.0,0,0,0,0,0,0,0
4638,(주)신성이엔지,104110,2015/12,3.35,6375993.0,59190825.0,0,0,0,0,0,0,0

In [95]:
df[df['회사명'] == '삼성물산(주)']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,이자_부실,현금흐름_부실,자본_부실,부실
430,삼성물산(주),830,2010/12,5.47,-3.001112e+08,8.578350e+09,0,-1,0,0,0,0,0
431,삼성물산(주),830,2011/12,4.14,-3.124720e+08,9.485056e+09,0,-1,0,0,0,0,0
432,삼성물산(주),830,2012/12,3.28,6.325311e+08,1.168927e+10,0,0,0,0,0,0,0
433,삼성물산(주),830,2013/12,3.76,4.274514e+08,1.141955e+10,0,0,0,0,0,0,0
434,삼성물산(주),830,2014/12,5.46,8.249434e+08,1.367244e+10,0,0,0,0,0,0,0
435,삼성물산(주),28260,2010/12,36.66,2.107358e+08,4.322132e+09,0,0,0,0,0,0,0
436,삼성물산(주),28260,2011/12,34.20,1.718036e+08,3.774253e+09,0,0,0,0,0,0,0
437,삼성물산(주),28260,2012/12,6.08,-1.893160e+07,3.805207e+09,0,-1,0,0,0,0,0
438,삼성물산(주),28260,2013/12,2.50,2.348403e+08,3.949133e+09,0,0,0,0,0,0,0
439,삼성물산(주),28260,2014/12,3.27,1.431139e+08,5.285290e+09,0,0,0,0,0,0,0
440,삼성물산(주),28260,2015/12,0.37,-6.234786e+07,1.831394e+10,-1,-1,0,0,0,0,0
441,삼성물산(주),28260,2016/12,0.67,1.355395e+09,2.110571e+10,-1,0,0,0,0,0,0
442,삼성물산(주),28260,2017/12,5.15,1.312436e+09,2.515125e+10,0,0,0,0,0,0,0
443,삼성물산(주),28260,2018/12,5.87,1.678377e+09,2.254894e+10,0,0,0,0,0,0,0
444,삼성물산(주),28260,2019/12,6.42,7.708496e+08,2.669210e+10,0,0,0,0,0,0,0
445,삼성물산(주),28260,2020/12,9.07,1.267897e+09,3.294548e+10,0,0,0,0,0,0,0
446,삼성물산(주),28260,2021/12,12.85,1.195732e+09,3.335244e+10,0,0,0,0,0,0,0
447,삼성물산(주),28260,2022/12,13.42,2.618286e+09,3.196412e+10,0,0,0,0,0,0,0

In [96]:
df[df['회사명'] == '한국제지(주)']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,이자_부실,현금흐름_부실,자본_부실,부실
1185,한국제지(주),2300,2010/12,5.26,9416443.0,462210949.0,0,0,0,0,0,0,0
1186,한국제지(주),2300,2011/12,4.08,69205929.0,466069634.0,0,0,0,0,0,0,0
1187,한국제지(주),2300,2012/12,4.42,14188201.0,473442984.0,0,0,0,0,0,0,0
1188,한국제지(주),2300,2013/12,2.55,15711046.0,503938293.0,0,0,0,0,0,0,0
1189,한국제지(주),2300,2014/12,2.91,24936152.0,507298471.0,0,0,0,0,0,0,0
1190,한국제지(주),2300,2015/12,9.48,-40137801.0,512362172.0,0,-1,0,0,0,0,0
1191,한국제지(주),2300,2016/12,13.16,26882825.0,523024814.0,0,0,0,0,0,0,0
1192,한국제지(주),2300,2017/12,5.32,1471877.0,520587520.0,0,0,0,0,0,0,0
1193,한국제지(주),2300,2018/12,-2.65,-33062812.0,486485836.0,-1,-1,0,0,0,0,0
1194,한국제지(주),2300,2019/12,0.62,68905899.0,487135934.0,-1,0,0,0,0,0,0
1195,한국제지(주),27970,2010/12,0.70,8833035.0,33542913.0,-1,0,0,1,0,0,1
1196,한국제지(주),27970,2011/12,-0.19,-2533841.0,34198914.0,-1,-1,0,1,0,0,1
1197,한국제지(주),27970,2012/12,-1.04,663250.0,84491870.0,-1,0,0,1,0,0,1
1198,한국제지(주),27970,2013/12,-0.69,-14948477.0,22669224.0,-1,-1,0,1,0,0,1
1199,한국제지(주),27970,2014/12,-0.39,-1891018.0,9745441.0,-1,-1,0,1,0,0,1
1200,한국제지(주),27970,2015/12,-1.59,-13541738.0,3342561.0,-1,-1,0,1,1,0,1
1201,한국제지(주),27970,2016/12,2.30,5897049.0,12693134.0,0,0,0,0,0,0,0
1202,한국제지(주),27970,2017/12,0.17,-3280580.0,18601874.0,-1,-1,0,0,0,0,0
1203,한국제지(주),27970,2018/12,2.06,9613185.0,26839659.0,0,0,0,0,0,0,0
1204,한국제지(주),27970,2019/12,2.97,14555816.0,37909539.0,0,0,0,0,0,0,0
1205,한국제지(주),27970,2020/12,6.85,30733035.0,87770913.0,0,0,0,0,0,0,0
1206,한국제지(주),27970,2021/12,9.33,16698312.0,97946294.0,0,0,0,0,0,0,0
1207,한국제지(주),27970,2022/12,2.13,6283893.0,101282896.0,0,0,0,0,0,0,0

In [97]:
## 한국제지[27970] 이자보상배율이 한국제지[2300]에 영향을 받아서 잘못 라벨링되어있음
df.iloc[[1195,1196],-1] = 0
df.iloc[[1195,1196],-4] = 0

In [98]:
## 중간에 비어서 라벨링이 잘못된 데이터 확인

In [99]:
df[df['회사명'] == '(주)유니켐']
## 중간에 비기전에 이미 부실로 라벨이 되어있어 채우지 않아도됨

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,이자_부실,현금흐름_부실,자본_부실,부실
4483,(주)유니켐,11330,2010/12,1.58,-6455708.0,26203078.0,0,-1,0,0,0,0,0
4484,(주)유니켐,11330,2011/12,-7.33,-1577789.0,9235781.0,-1,-1,0,0,0,0,0
4485,(주)유니켐,11330,2012/12,-3.86,-10144117.0,7945775.0,-1,-1,0,0,1,0,1
4486,(주)유니켐,11330,2013/12,-5.62,-12018072.0,11484861.0,-1,-1,0,1,1,0,1
4487,(주)유니켐,11330,2015/06,-3.20,-15286914.0,9518413.0,-1,-1,0,1,1,0,1
4488,(주)유니켐,11330,2016/12,2.00,-18122515.0,28457414.0,0,-1,0,0,1,0,1
4489,(주)유니켐,11330,2017/12,2.06,2074523.0,38188389.0,0,0,0,0,0,0,0
4490,(주)유니켐,11330,2018/12,6.86,-6829114.0,62849336.0,0,-1,0,0,0,0,0
4491,(주)유니켐,11330,2019/12,10.63,5869890.0,88716462.0,0,0,0,0,0,0,0
4492,(주)유니켐,11330,2020/12,4.69,19201728.0,103584544.0,0,0,0,0,0,0,0
4493,(주)유니켐,11330,2021/12,1.71,25847100.0,127961100.0,0,0,0,0,0,0,0
4494,(주)유니켐,11330,2022/12,0.52,23431308.0,139168129.0,-1,0,0,0,0,0,0

In [100]:
df.to_csv('코스피_라벨링_최종.csv')

## 코스닥 라벨링 수정

In [101]:
df = pd.read_csv('코스닥_라벨링.csv', index_col = 0)
df = df.reset_index(drop=True)

### 동일 회사명에 다른 거래소코드로 인해 잘못라벨링된 데이터 수정

In [102]:
# '(주)엔케이맥스[262760] 이 [182400]의 영향을 받아 부실로 잘못 라벨링됨
df.iloc[[13167,13168],-1] = 0
df.iloc[[13167,13168],-3] = 0

In [103]:
df[df['회사명'] == '(주)엔케이맥스']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,이자_부실,현금흐름_부실,자본_부실,부실
13157,(주)엔케이맥스,182400,2013/12,-16.01,-2536573.0,-1853395.0,-1,-1,-1,0,0,0,1
13158,(주)엔케이맥스,182400,2014/12,-46.48,-5062595.0,-2395643.0,-1,-1,-1,0,0,0,1
13159,(주)엔케이맥스,182400,2015/12,-135.11,-7953238.0,28757414.0,-1,-1,0,1,1,0,1
13160,(주)엔케이맥스,182400,2016/12,-196.54,-10240909.0,40676303.0,-1,-1,0,1,1,0,1
13161,(주)엔케이맥스,182400,2017/12,8432098.32,-15264843.0,39949814.0,0,-1,0,0,1,0,1
13162,(주)엔케이맥스,182400,2018/12,-1333.66,-12513969.0,34883686.0,-1,-1,0,0,1,0,1
13163,(주)엔케이맥스,182400,2019/12,-156.90,-18244013.0,107512736.0,-1,-1,0,0,1,0,1
13164,(주)엔케이맥스,182400,2020/12,-122.23,-34717316.0,120000863.0,-1,-1,0,1,1,0,1
13165,(주)엔케이맥스,182400,2021/12,-129.12,-34155324.0,119901982.0,-1,-1,0,1,1,0,1
13166,(주)엔케이맥스,182400,2022/12,-247.45,-38063225.0,83221090.0,-1,-1,0,1,1,0,1
13167,(주)엔케이맥스,262760,2017/12,-4493653.05,-3832126.0,20661124.0,-1,-1,0,1,0,0,0
13168,(주)엔케이맥스,262760,2018/12,8432098.32,-9277561.0,40281416.0,0,-1,0,0,0,0,0

In [105]:
df.iloc[[12828],-1] = 1
df[df['회사명'] == '(주)이큐셀']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,이자_부실,현금흐름_부실,자본_부실,부실
12821,(주)이큐셀,160600,2013/12,1.06,438787.0,9780481.0,0,0,0,0,0,0,0
12822,(주)이큐셀,160600,2014/12,4.97,6656763.0,13255635.0,0,0,0,0,0,0,0
12823,(주)이큐셀,160600,2015/12,16.82,-3162076.0,31948359.0,0,-1,0,0,0,0,0
12824,(주)이큐셀,160600,2016/12,0.66,1562405.0,32542609.0,-1,0,0,0,0,0,0
12825,(주)이큐셀,160600,2017/12,3.29,-1232880.0,36713879.0,0,-1,0,0,0,0,0
12826,(주)이큐셀,160600,2018/12,6.53,7136057.0,36703812.0,0,0,0,0,0,0,0
12827,(주)이큐셀,160600,2019/12,-16.89,-18682596.0,16974514.0,-1,-1,0,0,0,0,0
12828,(주)이큐셀,160600,2021/06,-1.59,-16634378.0,15026071.0,-1,-1,0,0,0,0,1
12829,(주)이큐셀,160600,2022/12,3.61,2080618.0,45136870.0,0,0,0,0,0,0,0

In [106]:
df.to_csv('코스닥_라벨링_최종.csv')