In [49]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv('코스피_라벨링.csv', index_col = 0)

In [62]:
df = df.reset_index(drop=True)
temp = df[df['회사명'] == '에스케이(주)']
ind = temp[df['거래소코드'] == 3600].index
df = df.drop(index = ind)

C:\Users\geonh\AppData\Local\Temp\ipykernel_41756\4127036508.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ind = temp[df['거래소코드'] == 3600].index

In [63]:
df = df.drop(index = df[df['회사명'] == '평산차업집단유한공사'].index)
df = df.reset_index(drop=True)

In [67]:
df.iloc[[1195,1196],-1] = 0
df[df['회사명'] == '한국제지(주)']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,부실
1185,한국제지(주),2300,2010/12,5.26,9416443.0,462210949.0,0,0,0,0
1186,한국제지(주),2300,2011/12,4.08,69205929.0,466069634.0,0,0,0,0
1187,한국제지(주),2300,2012/12,4.42,14188201.0,473442984.0,0,0,0,0
1188,한국제지(주),2300,2013/12,2.55,15711046.0,503938293.0,0,0,0,0
1189,한국제지(주),2300,2014/12,2.91,24936152.0,507298471.0,0,0,0,0
1190,한국제지(주),2300,2015/12,9.48,-40137801.0,512362172.0,0,-1,0,0
1191,한국제지(주),2300,2016/12,13.16,26882825.0,523024814.0,0,0,0,0
1192,한국제지(주),2300,2017/12,5.32,1471877.0,520587520.0,0,0,0,0
1193,한국제지(주),2300,2018/12,-2.65,-33062812.0,486485836.0,-1,-1,0,0
1194,한국제지(주),2300,2019/12,0.62,68905899.0,487135934.0,-1,0,0,0
1195,한국제지(주),27970,2010/12,0.70,8833035.0,33542913.0,-1,0,0,0
1196,한국제지(주),27970,2011/12,-0.19,-2533841.0,34198914.0,-1,-1,0,0
1197,한국제지(주),27970,2012/12,-1.04,663250.0,84491870.0,-1,0,0,1
1198,한국제지(주),27970,2013/12,-0.69,-14948477.0,22669224.0,-1,-1,0,1
1199,한국제지(주),27970,2014/12,-0.39,-1891018.0,9745441.0,-1,-1,0,1
1200,한국제지(주),27970,2015/12,-1.59,-13541738.0,3342561.0,-1,-1,0,1
1201,한국제지(주),27970,2016/12,2.30,5897049.0,12693134.0,0,0,0,0
1202,한국제지(주),27970,2017/12,0.17,-3280580.0,18601874.0,-1,-1,0,0
1203,한국제지(주),27970,2018/12,2.06,9613185.0,26839659.0,0,0,0,0
1204,한국제지(주),27970,2019/12,2.97,14555816.0,37909539.0,0,0,0,0
1205,한국제지(주),27970,2020/12,6.85,30733035.0,87770913.0,0,0,0,0
1206,한국제지(주),27970,2021/12,9.33,16698312.0,97946294.0,0,0,0,0
1207,한국제지(주),27970,2022/12,2.13,6283893.0,101282896.0,0,0,0,0

In [68]:
df.to_csv('코스피_라벨링_최종.csv')

In [79]:
df = pd.read_csv('코스닥_라벨링.csv', index_col = 0)

In [80]:
df = df.reset_index(drop=True)

In [81]:
df.iloc[[13261,13262],-1] = 0
df[df['회사명'] == '(주)엔케이맥스']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,부실
13251,(주)엔케이맥스,182400,2013/12,-16.01,-2536573.0,-1853395.0,-1,-1,-1,1
13252,(주)엔케이맥스,182400,2014/12,-46.48,-5062595.0,-2395643.0,-1,-1,-1,1
13253,(주)엔케이맥스,182400,2015/12,-135.11,-7953238.0,28757414.0,-1,-1,0,1
13254,(주)엔케이맥스,182400,2016/12,-196.54,-10240909.0,40676303.0,-1,-1,0,1
13255,(주)엔케이맥스,182400,2017/12,8432098.32,-15264843.0,39949814.0,0,-1,0,1
13256,(주)엔케이맥스,182400,2018/12,-1333.66,-12513969.0,34883686.0,-1,-1,0,1
13257,(주)엔케이맥스,182400,2019/12,-156.90,-18244013.0,107512736.0,-1,-1,0,1
13258,(주)엔케이맥스,182400,2020/12,-122.23,-34717316.0,120000863.0,-1,-1,0,1
13259,(주)엔케이맥스,182400,2021/12,-129.12,-34155324.0,119901982.0,-1,-1,0,1
13260,(주)엔케이맥스,182400,2022/12,-247.45,-38063225.0,83221090.0,-1,-1,0,1
13261,(주)엔케이맥스,262760,2017/12,-4493653.05,-3832126.0,20661124.0,-1,-1,0,0
13262,(주)엔케이맥스,262760,2018/12,8432098.32,-9277561.0,40281416.0,0,-1,0,0

In [82]:
df.iloc[[12910],-1] = 1
df[df['회사명'] == '(주)이큐셀']

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS연결),영업활동으로 인한 현금흐름(간접법)(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),이자보상배율,현금흐름,자본,부실
12903,(주)이큐셀,160600,2013/12,1.06,438787.0,9780481.0,0,0,0,0
12904,(주)이큐셀,160600,2014/12,4.97,6656763.0,13255635.0,0,0,0,0
12905,(주)이큐셀,160600,2015/12,16.82,-3162076.0,31948359.0,0,-1,0,0
12906,(주)이큐셀,160600,2016/12,0.66,1562405.0,32542609.0,-1,0,0,0
12907,(주)이큐셀,160600,2017/12,3.29,-1232880.0,36713879.0,0,-1,0,0
12908,(주)이큐셀,160600,2018/12,6.53,7136057.0,36703812.0,0,0,0,0
12909,(주)이큐셀,160600,2019/12,-16.89,-18682596.0,16974514.0,-1,-1,0,0
12910,(주)이큐셀,160600,2021/06,-1.59,-16634378.0,15026071.0,-1,-1,0,1
12911,(주)이큐셀,160600,2022/12,3.61,2080618.0,45136870.0,0,0,0,0

In [84]:
sp_enp =['(주)본느','(주)세화피앤씨','(주)아이엘사이언스','(주)알로이스','(주)에스에이티','(주)원바이오젠','(주)원익피앤이','(주)인산가','(주)자비스','(주)정다운','(주)카이노스메드','(주)티에스트릴리온','(주)포인트엔지니어링','(주)한국비엔씨','(주)휴럼','나무기술(주)','씨아이에스(주)','엠에프엠코리아(주)','원텍(주)','패션플랫폼(주)']

In [85]:
for i in sp_enp:
    ind = df[df['회사명'] == i].index
    df = df.drop(index = ind).reset_index(drop=True)

In [87]:
df.to_csv('코스닥_라벨링_최종.csv')