In [122]:
import pandas as pd

df = pd.read_excel("C:/Users/SAMSUNG/Documents/vscode/2024/ML/프로젝트/data/장단기금리스프레드_PRE.xlsx")
df.drop([0,1,2,3,4,5],inplace=True)
df.rename(columns={'Unnamed: 1':'국고채(3년) - 기준금리(%p)',
                   'Unnamed: 2':'국고채(3년) - 통화안정증권(91일)(%p)',
                   'Unnamed: 3':'국고채(10년) - 국고채(3년)(%p)',
                   '장단기 금리 스프레드':'기간'}, inplace=True)
df

,기간,국고채(3년) - 기준금리(%p),국고채(3년) - 통화안정증권(91일)(%p),국고채(10년) - 국고채(3년)(%p)
6,2012-12-03,0.09,0.04,0.19
7,2012-12-04,0.09,0.05,0.2
8,2012-12-05,0.11,0.06,0.22
9,2012-12-06,0.08,0.05,0.24
10,2012-12-07,0.06,0.04,0.25
...,...,...,...,...
2805,2024-04-03,-0.159,-0.124,0.111
2806,2024-04-04,-0.162,-0.124,0.119
2807,2024-04-05,-0.171,-0.126,0.104
2808,2024-04-08,NaN,-0.085,0.105
2809,2024-04-09,NaN,-0.079,0.112

In [123]:
df['기간'] = pd.to_datetime(df['기간'])
df

,기간,국고채(3년) - 기준금리(%p),국고채(3년) - 통화안정증권(91일)(%p),국고채(10년) - 국고채(3년)(%p)
6,2012-12-03,0.09,0.04,0.19
7,2012-12-04,0.09,0.05,0.2
8,2012-12-05,0.11,0.06,0.22
9,2012-12-06,0.08,0.05,0.24
10,2012-12-07,0.06,0.04,0.25
...,...,...,...,...
2805,2024-04-03,-0.159,-0.124,0.111
2806,2024-04-04,-0.162,-0.124,0.119
2807,2024-04-05,-0.171,-0.126,0.104
2808,2024-04-08,NaN,-0.085,0.105
2809,2024-04-09,NaN,-0.079,0.112

In [124]:
df = df.groupby(df['기간'].dt.to_period('M')).mean().reset_index(drop=True)
df

,기간,국고채(3년) - 기준금리(%p),국고채(3년) - 통화안정증권(91일)(%p),국고채(10년) - 국고채(3년)(%p)
0,2012-12-15 15:09:28.421052672,0.1,0.061053,0.284737
1,2013-01-16 16:21:49.090909184,-0.005,0.026818,0.305909
2,2013-02-15 07:34:44.210526208,-0.045263,0.020526,0.338947
3,2013-03-16 12:00:00.000000000,-0.15,-0.0025,0.3095
4,2013-04-14 22:54:32.727272704,-0.199545,-0.075,0.287273
...,...,...,...,...
132,2023-12-15 07:12:00.000000000,-0.15045,-0.17305,0.06515
133,2024-01-16 07:38:10.909090816,-0.234182,-0.150227,0.087273
134,2024-02-15 21:28:25.263158016,-0.149158,-0.080053,0.077842
135,2024-03-16 12:00:00.000000000,-0.1904,-0.1532,0.0799
136,2024-04-04 13:42:51.428571392,-0.1736,-0.12,0.104714

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   기간                         137 non-null    datetime64[ns]
 1   국고채(3년) - 기준금리(%p)         137 non-null    object
 2   국고채(3년) - 통화안정증권(91일)(%p)  137 non-null    object
 3   국고채(10년) - 국고채(3년)(%p)     137 non-null    object
dtypes: datetime64[ns](1), object(3)
memory usage: 4.4+ KB

In [126]:
df['증감_국고채(3년)_기준금리'] = (df['국고채(3년) - 기준금리(%p)'] - df['국고채(3년) - 기준금리(%p)'].shift(1)) / df['국고채(3년) - 기준금리(%p)'].shift(1)
df['증감_국고채(3년)_통화안정증권(91일)'] = (df['국고채(3년) - 통화안정증권(91일)(%p)'] - df['국고채(3년) - 통화안정증권(91일)(%p)'].shift(1)) / df['국고채(3년) - 통화안정증권(91일)(%p)'].shift(1)
df['증감_국고채(10년)_국고채(3년)'] = (df['국고채(10년) - 국고채(3년)(%p)'] - df['국고채(10년) - 국고채(3년)(%p)'].shift(1)) / df['국고채(10년) - 국고채(3년)(%p)'].shift(1)
df['기간'] = df['기간'].dt.strftime('%Y-%m')

In [127]:
df.to_excel('C:/Users/SAMSUNG/Documents/vscode/2024/ML/프로젝트/data/장단기금리스프레드_PRE2.xlsx')

In [128]:
df

,기간,국고채(3년) - 기준금리(%p),국고채(3년) - 통화안정증권(91일)(%p),국고채(10년) - 국고채(3년)(%p),증감_국고채(3년)_기준금리,증감_국고채(3년)_통화안정증권(91일),증감_국고채(10년)_국고채(3년)
0,2012-12,0.1,0.061053,0.284737,NaN,NaN,NaN
1,2013-01,-0.005,0.026818,0.305909,-1.05,-0.560737,0.074357
2,2013-02,-0.045263,0.020526,0.338947,8.052632,-0.234612,0.108
3,2013-03,-0.15,-0.0025,0.3095,2.313953,-1.121795,-0.086879
4,2013-04,-0.199545,-0.075,0.287273,0.330303,29.0,-0.071817
...,...,...,...,...,...,...,...
132,2023-12,-0.15045,-0.17305,0.06515,-1.554236,-2.056061,-0.448306
133,2024-01,-0.234182,-0.150227,0.087273,0.556542,-0.131885,0.339566
134,2024-02,-0.149158,-0.080053,0.077842,-0.363068,-0.467123,-0.108059
135,2024-03,-0.1904,-0.1532,0.0799,0.2765,0.913741,0.026437
136,2024-04,-0.1736,-0.12,0.104714,-0.088235,-0.21671,0.310567